In [5]:
pip install torch

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

  Using cached torch-2.5.0-cp311-cp311-win_amd64.whl.metadata (28 kB)
  Using cached filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
  Using cached networkx-3.4.1-py3-none-any.whl.metadata (6.3 kB)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
  Using cached fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)
  Using cached sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
   ---------------------------------------- 0.0/203.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/203.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/203.1 MB ? eta -:--:--
   ---------------------------------------- 0.5/203.1 MB 728.2 kB/s eta 0:04:39
   ---------------------------------------- 0.5/203.1 MB 728.2 kB/s eta 0:04:39
   --------------------------

In [2]:
import torch
import numpy as np

In [3]:
data = [
[1,2],
[3,4]
]
x = torch.tensor(data)
print(type(x))

<class 'torch.Tensor'>


In [42]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)
print(type(x_np))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
<class 'torch.Tensor'>


In [5]:
x_ones = torch.ones_like(x)
print("One Tensor: \n",x_ones)
x_rand = torch.rand_like(x,dtype=torch.float)
print(x_rand)

One Tensor: 
 tensor([[1, 1],
        [1, 1]])
tensor([[0.1456, 0.4030],
        [0.6171, 0.9949]])


In [8]:
shape = (2, 3)
random_tensor = torch.rand(shape)
print(random_tensor)
print(type(random_tensor))

ones_tensor = torch.ones(shape)
print(ones_tensor)
print(type(ones_tensor))

zeros_tensor = torch.zeros(shape)
print(zeros_tensor)
print(type(zeros_tensor))

tensor([[0.2778, 0.7379, 0.5195],
        [0.1877, 0.7286, 0.5641]])
<class 'torch.Tensor'>
tensor([[1., 1., 1.],
        [1., 1., 1.]])
<class 'torch.Tensor'>
tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>


In [10]:
tensor = torch.rand(3, 4)
print(tensor)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

tensor([[0.4111, 0.4595, 0.6735, 0.0586],
        [0.3514, 0.5488, 0.2337, 0.5806],
        [0.6585, 0.3581, 0.7621, 0.1971]])
torch.Size([3, 4])
torch.float32
cpu


In [11]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print("Device tensor is stored in ", tensor.device)

In [12]:
print(tensor.device)

cpu


In [13]:
tensor = torch.ones(4, 4)
print(tensor)
tensor1 = torch.zeros(4, 4)
print(tensor1)
tensor2 = torch.cat([tensor, tensor1])
print(tensor2)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [30]:
tensor.mul(tensor1)
tensor * tensor1
tensor.T


tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [15]:
tensor.add_(3)
print(tensor)


tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


In [16]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)
print(type(n))


tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
